{
 "title": "Example Relayer Workflows",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ready Workflows",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (enqueued_workflows)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "In Progress Workflows",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (in_progress_workflows)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed Workflows",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (failed_workflows)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Retrying Workflows",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (delayed_workflows)", "legendFormat": "__auto" }
   ]
  }
 ]
}