{
 "title": "Relayer-Engine-Local-Monitoring",
 "time": { "from": "2023-03-16T17:14:29.173Z", "to": "2023-03-16T17:24:29.173Z" },
 "templating": {
  "list": [
   { "name": "logs_query" }
  ]
 },
 "panels": [
  {
   "title": "Ready Workflows",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (enqueued_workflows)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Wallet Balance by chain and wallet",
   "type": "table",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 0 },
   "targets": [
    { "expr": "wallet_balances", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "In Progress Workflows",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (in_progress_workflows)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 20, "x": 4, "y": 11 },
   "targets": [
    {
     "expr": "{job=\"relayer-example\"} |~ `.*$logs_query.*` | json labels=\"labels\", level=\"level\", message=\"message\" | level!=\"verbose\" | line_format `[{{upper .level}}]: {{.message}}`",
     "maxLines": 1000
    }
   ]
  },
  {
   "title": "Retrying Workflows",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (delayed_workflows)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed Workflows",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (failed_workflows)", "legendFormat": "__auto" }
   ]
  }
 ]
}